# Generated by Django 3.2.9 on 2022-05-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dc_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='XizmatSend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xizmat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.xizmat')),
            ],
        ),
    ]
